version: "3"

services:
  # kics-scan ignore-line
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    networks:
      - iamme-iamme
    cap_drop:
      - ALL
    # kics-scan ignore-line
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_DAC_OVERRIDE
      - CAP_SETGID
      - CAP_SETUID
    ports:
      - "127.0.0.1:7474:7474"
      - "0.0.0.0:7687:7687"
    volumes:
      - okta_Data:/data
    environment:
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_AUTH: $NEO4J_AUTH
      NEO4J_server_memory_heap_initial__size: ${NEO4J_server_memory_heap_initial__size}
      NEO4J_server_memory_heap_max__size: ${NEO4J_server_memory_heap_max__size}
      NEO4J_server_memory_pagecache_size: ${NEO4J_server_memory_pagecache_size}
      NEO4J_server_jvm_additional: "-XX:+ExitOnOutOfMemoryError"
      NEO4J_initial_dbms_default__database: "okta"
      NEO4J_dbms_cypher_forbid__shortestpath__common__nodes: "false"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 1m

networks:
  iamme-iamme:

volumes:
  okta_Data:
