name: Golang CI
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

concurrency:
  group: iamme-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@babf5448da25db0c3d47d0348fb3d6979e7fc555
    # v0.1.2

  build-and-test:
    uses: notdodo/github-actions/.github/workflows/go-build-and-test.yml@babf5448da25db0c3d47d0348fb3d6979e7fc555
    # v0.1.2
