name: Golang CI
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-ci.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-ci.yml"

concurrency:
  group: iamme-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@941851ae821e4fa40c1752cffda47b50f39949f5

  build-and-test:
    uses: notdodo/github-actions/.github/workflows/go-build-and-test.yml@941851ae821e4fa40c1752cffda47b50f39949f5
