name: Golang CI
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

concurrency:
  group: iamme-go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@cabf073f973a7074895d52d9ba3b59d5b05241ee
    # go-sec-v0.0.0

  build-and-test:
    uses: notdodo/github-actions/.github/workflows/go-ci.yml@3fa2e285bd272ae42a21fad0ffdf05066da2fa5f
    # go-ci-v0.0.0
