name: Golang CI
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - Dockerfile
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - Dockerfile

concurrency:
  group: iamme-go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@gitleaks-v0.0.1

  build-and-test:
    uses: notdodo/github-actions/.github/workflows/go-ci.yml@gitleaks-v0.0.1

  build-docker-image:
    if: ${{ github.event_name == 'pull_request' }}
    uses: notdodo/github-actions/.github/workflows/docker-build-and-push.yml@gitleaks-v0.0.1
    with:
      image: notdodo/iamm-iamme
      platforms: linux/amd64
      push: false
      registry: ghcr.io
    secrets:
      registry-username: notdodo
      registry-password: ${{ secrets.GITHUB_TOKEN }}
