name: Golang CI
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - Dockerfile
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - Dockerfile

concurrency:
  group: iamme-go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@go-sec-v0
    with:
      egress-policy-allowlist: >
        proxy.golang.org:443
        sum.golang.org:443
        objects.githubusercontent.com:443
        storage.googleapis.com:443

  build-and-test:
    uses: notdodo/github-actions/.github/workflows/go-ci.yml@go-ci-v0
    with:
      egress-policy-allowlist: >
        proxy.golang.org:443
        sum.golang.org:443
        objects.githubusercontent.com:443
        storage.googleapis.com:443
        raw.githubusercontent.com:443

  build-docker-image:
    if: ${{ github.event_name == 'pull_request' }}
    uses: notdodo/github-actions/.github/workflows/docker-build-and-push.yml@docker-build-and-push-v0
    with:
      image: notdodo/iamme-iamme
      platforms: linux/amd64
      push: false
      registry: ghcr.io
    secrets:
      registry-username: notdodo
      registry-password: ${{ secrets.GITHUB_TOKEN }}
