name: Go Build and Test
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: iamme-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        # v5.0.0
        with:
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc
        # v3.7.0
        with:
          version: latest

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        # v5.0.0
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build ./...
      - name: Test with the Go CLI
        run: go test ./...
