name: Golang CI
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

concurrency:
  group: iamme-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@f481e4d2cff7f15766729798dbb0811b5af6b700

  build-and-test:
    uses: notdodo/github-actions/.github/workflows/go-build-and-test.yml@f481e4d2cff7f15766729798dbb0811b5af6b700
