name: SAST
on:
  push:
    branches:
      - main
    # paths:
    #   - "**.go"
  pull_request:
    branches:
      - main
    # paths:
    #   - "**.go"

concurrency:
  group: iamme-gosec-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@main
