name: Infrastructure Security Scan
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.go"
      - "**.md"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.go"
      - "**.md"
      - "go.mod"
      - "go.sum"

concurrency:
  group: iamme-kics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-security-scan:
    uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@f7181d1dec278ef7b8bafbbbed2ab55e2dbcca7b
    # v0.1.2
